tabs not spaces

diff --git a/sync-settings/files/sync-settings.init b/sync-settings/files/sync-settings.init
--- a/sync-settings/files/sync-settings.init
+++ b/sync-settings/files/sync-settings.init
@@ -11,23 +11,23 @@ boot() {
 	if [ ! -f /etc/config/settings.json ]; then
 		logger -t "sync-settings" "Creating /etc/config/settings.json"
 		/usr/bin/sync-settings -c -n -v force=true | logger -t "sync-settings"
-        sync_settings_status=$?
+		sync_settings_status=$?
 	else
 		/usr/bin/sync-settings -u -n -v force=true | logger -t "sync-settings"
-        sync_settings_status=$?
+		sync_settings_status=$?
 	fi
 
-    if [ $sync_settings_status -eq 0 ] && [ -e /mnt/flash/mfw-settings/hybrid ]; then
-        logger -t "sync-settings" "Notifying Packetd in EOS to reload the settings file..."
-        signal_output=$(/usr/bin/updateSysdbSignal --sighup 2>&1)
-        signal_status=$?
+	if [ $sync_settings_status -eq 0 ] && [ -e /mnt/flash/mfw-settings/hybrid ]; then
+		logger -t "sync-settings" "Notifying Packetd in EOS to reload the settings file..."
+		signal_output=$(/usr/bin/updateSysdbSignal --sighup 2>&1)
+		signal_status=$?
 
-        if [ $signal_status -eq 0 ]; then
-            logger -t "sync-settings" "Notified Packetd in EOS to reload the settings file successfully"
-        else
-            logger -t "sync-settings" "Failed to notify Packetd in EOS to reload the settings file: $signal_output"
-        fi
-    fi
+		if [ $signal_status -eq 0 ]; then
+			logger -t "sync-settings" "Notified Packetd in EOS to reload the settings file successfully"
+		else
+			logger -t "sync-settings" "Failed to notify Packetd in EOS to reload the settings file: $signal_output"
+		fi
+	fi
 
 	# ensure we have an up to date defaults.json file
 	/usr/bin/sync-settings -c -s -f /tmp/settings.json
