okay logs don't work so removed them

diff --git a/sync-settings/files/sync-settings.init b/sync-settings/files/sync-settings.init
--- a/sync-settings/files/sync-settings.init
+++ b/sync-settings/files/sync-settings.init
@@ -4,22 +4,40 @@
 START=14
 STOP=14
 
+LOG_FILE=/tmp/sync_settings_boot.log
+
+write_log() {
+	echo "$(date "+%Y-%m-%d %H:%M:%S") - $1" >> "$LOG_FILE"
+}
+
 boot() {
+	touch "$LOG_FILE"
+	write_log "Running sync-settings for system initialization."
+
 	# check if we should reset settings
 	/usr/bin/check-for-usb-reset.sh && rm /etc/config/settings.json
-	
-	touch /tmp/sync-settings-boot-log
-
 	if [ ! -f /etc/config/settings.json ]; then
-		/usr/bin/sync-settings -c -n -v force=true
+		write_log "Creating /etc/config/settings.json"
+		output=$(/usr/bin/sync-settings -c -n -v force=true)
 		sync_settings_status=$?
+		write_log "$output"
 	else
-		/usr/bin/sync-settings -u -n -v force=true
+		output=$(/usr/bin/sync-settings -u -n -v force=true)
 		sync_settings_status=$?
+		write_log "$output"
 	fi
 
+	write_log "sync-settings command status: $sync_settings_status"
 	if [ $sync_settings_status -eq 0 ] && [ -e /etc/config/hybrid ]; then
-		/usr/bin/updateSysdbSignal --sighup
+		write_log "Notifying Packetd in EOS to reload the settings file..."
+		signal_output=$(/usr/bin/updateSysdbSignal --sighup 2>&1)
+		signal_status=$?
+
+		if [ $signal_status -eq 0 ]; then
+			logger -t "sync-settings" "Notified Packetd in EOS to reload the settings file successfully"
+		else
+			logger -t "sync-settings" "Failed to notify Packetd in EOS to reload the settings file: $signal_output"
+		fi
 	fi
 
 	# ensure we have an up to date defaults.json file
