added it the pyconnector startup with logs

diff --git a/pyconnector/files/pyconnector.init b/pyconnector/files/pyconnector.init
--- a/pyconnector/files/pyconnector.init
+++ b/pyconnector/files/pyconnector.init
@@ -28,6 +28,31 @@ get_translated_host()
 	eval "$__return_host=$host"
 }
 
+# Wait for restd to come up to prevent a race condition where
+# pyconnector starts first, but sends incomplete information 
+# since the api enpoints from restd couldn't send back system status info
+wait_for_restd_start() {
+    local endpoint="health"
+    local max_retries=20
+    local retry_delay=1
+    local url="http://localhost/api/${endpoint}"
+
+    for attempt in $(seq 1 $max_retries); do
+        response=$(curl -s "$url")
+        if [ $? -eq 0 ]; then
+            status=$(echo "$response" | jq -r '.status')
+            logger -t pyconnector "restd status: $status. Starting pyconnector"
+            return
+        else
+            logger -t pyconnector "Attempt $attempt to reach restd failed. Error: $response"
+            sleep "$retry_delay"
+        fi
+    done
+
+    logger -t pyconnector "restd failed to start after $((max_retries * retry_delay)) seconds. Continuing..."
+}
+
+
 start_service() {
     CLOUD=`jsonfilter -i /etc/config/current.json -e '@["system"]["cloud"]'`
     # If there are no cloud settings, just enable cloud access
@@ -39,6 +64,8 @@ start_service() {
     fi
 
     if [ $ENABLED = "true" ] ; then
+        wait_for_restd_start
+
         SERVERS=`jsonfilter -i /etc/config/current.json -e '@["system"]["cloud"]["cloudServers"]' | tr -d ',"[]'`
 
         for server in $SERVERS ; do
