MFW-1050: wan-manager: added table verification for nft

diff --git a/wan-manager/files/wan-manager b/wan-manager/files/wan-manager
--- a/wan-manager/files/wan-manager
+++ b/wan-manager/files/wan-manager
@@ -3,6 +3,18 @@
 . /lib/functions/network.sh
 . /usr/share/libubox/jshn.sh
 
+check_for_table()
+{
+	ipCheck=$1
+	tableCheck=$2
+	output=`nft list table $ipCheck $tableCheck`
+	retval=$?
+	if [ $retval -ne 0 ]; then
+		echo "NFT does not have a required table for wan-manager"
+		exit 1
+	fi
+}
+
 handle_term()
 {
 	for i in `pgrep -P $$ `
@@ -626,6 +638,9 @@ test()
 		done
 	done
 }
+
+check_for_table ip wan-routing
+check_for_table ip6 wan-routing
 
 trap 'handle_term' TERM INT
 rm -rf /tmp/wan_status/*
